site_name: UNIHACK Handbook
theme_dir: theme/cinder
pages:
  - Home: 'index.md'
  - Melbourne:
      - Home: 'melbourne/index.md'
      - Mixer Night: 'melbourne/mixer-night.md'
      - Sponsors: 'melbourne/sponsors.md'
      - Provided Tools: 'melbourne/tools.md'
      - Event Info:
        - Venue: 'melbourne/event-information/venue.md'
        - Schedule: 'melbourne/event-information/schedule.md'
        - Participant Info: 'melbourne/event-information/participants.md'
        - Communication Tools: 'melbourne/event-information/communication.md'
        - Hardware Safety: 'melbourne/event-information/hardware.md'
        - Rules: 'melbourne/event-information/rules.md'
      - Judging:
        - Guidelines/Criteria: 'melbourne/judging/index.md'
        - DevPost Submission: 'melbourne/judging/submission.md'
      - Safety:
        - Code of Conduct: 'melbourne/safety/code-of-conduct.md'
        - Emergency Contacts: 'melbourne/safety/emergency.md'
  - Sydney:
        - Home: 'sydney/index.md'
        - Event Info:
            - Venue: 'sydney/event-information/venue.md'
            - Participant Information: 'sydney/event-information/participants.md'
            - Schedule: 'sydney/event-information/schedule.md'
            - Hardware: 'sydney/event-information/hardware.md'
            - Tech Talks: 'sydney/event-information/tech-talks.md'
            - Rules: 'sydney/event-information/rules.md'
        - Judging:
            - Guidelines/Criteria: 'sydney/judging/index.md'
            - DevPost Submission: 'sydney/judging/submission.md'
        - Safety:
            - Code of Conduct: 'sydney/safety/code-of-conduct.md'
            - Emergency Contacts: 'sydney/safety/emergency.md'
  - Changelog: 'changelog.md'
