site_name: UNIHACK Handbook
theme_dir: theme/cinder
pages:
  - Home: 'index.md'
  - Melbourne:
      - Home: 'melbourne/index.md'
      - Mixer Night: 'melbourne/mixer-night.md'
      - Event Info:
        - Venue: 'melbourne/event-information/venue.md'
        - Participant Information: 'melbourne/event-information/participants.md'
        - Schedule: 'melbourne/event-information/schedule.md'
        - Rules: 'melbourne/event-information/rules.md'
      - Judging:
        - Guidelines/Criteria: 'melbourne/judging/index.md'
        - DevPost Submission: 'melbourne/judging/submission.md'
      - Safety:
        - Code of Conduct: 'melbourne/safety/code-of-conduct.md'
        - Emergency Contacts: 'melbourne/safety/emergency.md'
  - Sydney: 'sydney/index.md'
  - Changelog: 'changelog.md'
